### ISSUE TITLE
User List: Filter by Journal

### ISSUE THREAD

**Issue by ajrbyers** [openlibhums/janeway#1962]
**Is your feature request related to a problem? Please describe.**
Sometimes the User list is very long.

**Describe the solution you'd like**
Allow editors to filer the list by users who already have a role in their journal.

**Describe alternatives you've considered**
None.

**Additional context**
Request from editor at Michigan.

**Comment by ajrbyers** [comment]
The user list page no longer presents users with a long list of users and allows editors instead to search for them. I'm not entirely sure if having a flag to filter by users who currently have a role in the journal would be useful anymore.

Thoughts @mauromsl @joemull @StephDriver @S-Haime

**Comment by S-Haime** [comment]
I don't feel that going by role would be particularly helpful - it assumes that a user is a) active and b) has the correct role assigned. More often than not, one of these is not met when there are issues. Searching by name makes more sense to me? The only ones where I may wish to have overview as an editor/manager is a) to see who else has editor permissions and b) some of the peer review overviews. Though the latter are already addressed through reporting.

**Comment by joemull** [comment]
I think having a general-purpose list where you can filter AND search would be best for a range of use cases. This way, the filter will provide a convenience if the data is good, and otherwise a search can be used to find and troubleshoot a particular name.

Maybe we can combine this one in https://github.com/BirkbeckCTP/janeway/issues/4185?

**Comment by mauromsl** [comment]
For me these issues stem from the fact that there are at least 4 user list views which all display slightly different data and have different options:
 1. Enrolled users
 2. Enrol Users
 3. Roles > Role > users
 4. Inactive Users
 
The request on this issue is addressed by option 3 above.
I think a better approach to reduce the number of views and consolidating the displayed data and available actions (e.g some views have the control user option, others have the edit user option, one has a filter by role baked in, another one has a bulk assign role...)

Personally, I'd consolidate all this views into a single user manager.

**Comment by ajrbyers** [comment]
> For me these issues stem from the fact that there are at least 4 user list views which all display slightly different data and have different options:
> 
>     1. Enrolled users
> 
>     2. Enrol Users
> 
>     3. Roles > Role > users
> 
>     4. Inactive Users
> 
> 
> The request on this issue is addressed by option 3 above. I think a better approach would be to reduce the number of views and consolidating the displayed data and available actions (e.g some views have the control user option, others have the edit user option, one has a filter by role baked in, another one has a bulk assign role...)
> 
> Personally, I'd consolidate all this views into a single user manager.

We definitely started this process with the changes to enrol users, but I think @joemull suggestion might do the trick. Having a configurable CBV that we can use to generate the lists of users would be a good way to do this.

**Comment by S-Haime** [comment]
I absolutely agree with @mauromsl I thought we couldnt do the single list for some reason ( I feel like we discussed this before). The 4 different ones drives me insane.

@joemull's suggestion sounds good.

**Comment by ajrbyers** [comment]
> I absolutely agree with @mauromsl I thought we couldnt do the single list for some reason ( I feel like we discussed this before). The 4 different ones drives me insane.
> 
> @joemull's suggestion sounds good.

I don't think there was a particular reason other than "its always been that way and we don't have time to fix it" XD

**Comment by S-Haime** [comment]
> > I absolutely agree with @mauromsl I thought we couldnt do the single list for some reason ( I feel like we discussed this before). The 4 different ones drives me insane.
> > @joemull's suggestion sounds good.
> 
> I don't think there was a particular reason other than "its always been that way and we don't have time to fix it" XD

_bruh_

**Comment by ajrbyers** [comment]
> > > I absolutely agree with @mauromsl I thought we couldnt do the single list for some reason ( I feel like we discussed this before). The 4 different ones drives me insane.
> > > @joemull's suggestion sounds good.
> > 
> > 
> > I don't think there was a particular reason other than "its always been that way and we don't have time to fix it" XD
> 
> _bruh_

Did you just _bruh_ at me? What are we? Gen Alpha? 🤣

**Comment by joemull** [comment]
Agree wholeheartedly with the difficulty of the existing separate views. I think we should try to consolidate the existing ones as much as possible into the new general one. It may be we can use inline buttons in the results of that list that go out to separate views for most of the functionality (or potentially bulk actions, but will try to avoid as we don't have a good UI pattern for that). Will give it a whirl!
