### ISSUE TITLE
Public preprint item page should display item stats 

### ISSUE THREAD

**Issue by alainna** [openlibhums/janeway#2633]
**Is your feature request related to a problem? Please describe.**

As an author of a preprint, I want to be able to easily find statistics about my preprint by going directly to the item page -- I shouldn't need to log into my author dashboard to see my preprint's view/download stats. 

**Describe the solution you'd like**

Preprint item pages should publicly display item view/download stats 

**Describe alternatives you've considered**

It could be a settings option repository admin could enable on a repository by repository basis

**Additional context**

![image](https://user-images.githubusercontent.com/15632391/143097118-49abb127-6c51-40a7-a0eb-167e7dbe4a47.png)

**Comment by ajrbyers** [comment]
This should probably be a setting to be enabled on a repository by repository basis.

**Comment by joemull** [comment]
Just to note for the record: this was completed by pull https://github.com/openlibhums/janeway/pull/4358. It now shows no changes and says it was closed without merging, but the branch was merged locally and pushed on master.
