### ISSUE TITLE
Optionally disallow editors from making changes with significant legal or operational impacts

### ISSUE THREAD

**Issue by hardyoyo** [openlibhums/janeway#3232]
**Is your feature request related to a problem? Please describe.**
Janeway distributes an impressive amount of responsibilities to editors. However, in some situations, this creates (for some organizations) unacceptable legal risks. Specifically, it is our opinion that the copyright statement and license options are only safely edited by administrators.

**Describe the solution you'd like**

For Copyright:
- Located in Submission Settings, but also accessible from All Settings.
- There are two settings: copyright_notice and copyright_submission_label
- In addition to restricting user input, would also need to prevent this item being removed from Submission Fields Configurator

For Licenses:
- Has its own settings page: Licence Manager. It is not listed in All Settings.
- Is present in Submission Fields Configurator, so would need to prevent users from removing it there.

For Email:
- Settings > General > Email > From Address (This should not be changeable / needs to always be set to our no-reply address, i.e. a change here can impact the system's ability to send e-mail *at all*).

**Describe alternatives you've considered**
Trust and documentation are options, however, this presents us with an unacceptable legal risk. The more journals we launch, the greater the overall risk of a mistake being made.

**Additional context**
Obviously, not every Janeway installation will be this risk-averse. This feature should therefore be toggleable in some way. We leave the implementation details for the developer.

One possible approach would be to build out the role configuration, to facilitate fine-grained permissions for the fields listed above. However, this is not a requirement.  Being able to limit write access to these fields to admin users *is* the only requirement.

**Comment by hardyoyo** [comment]
I'm tempted to add a new `is_legal_admin` to the Account model in core/models.py but I bet we may have feelings about doing such a thing... so I thought I'd mention it. There's probably a better way, via a User Role, but I'm having a hard time finding an example to follow.

**Comment by ajrbyers** [comment]
> I'm tempted to add a new `is_legal_admin` to the Account model in core/models.py but I bet we may have feelings about doing such a thing... so I thought I'd mention it. There's probably a better way, via a User Role, but I'm having a hard time finding an example to follow.

You can add a role, using a data migration to insert the role to the database and use that.

**Comment by hardyoyo** [comment]
related to #945 which will provide a role to be used to complete this ticket
