### ISSUE TITLE
Citation export

### ISSUE THREAD

**Issue by S-Haime** [openlibhums/janeway#3771]
[Reported by Harrison - Iowa]

An editor has reported the following happens when exporting a citation to Endnote:

"Katie R. Lybarger, E. S. B., K. J. F., L. A. E., L. N. D., M. C. H., J. L. V., M. D. Z, M. D. C., T. G. O. (2023). Determination of Consumer Color and Discoloration Thresholds for Purchase of Representative Retail Ground Beef. Meat and Muscle Biology, 7(1)."
 
When doing this using Zotero:

"Katie R. Lybarger, E. S. B., Kaylee J. Farmer, Lane A. Egger, Lindsey N. Drey, Melvin C. Hunt, Jessie L. Vipham, Morgan D. Zumbaugh, Michael D. Chao, Travis G. O’Quinn. (2023). Determination of Consumer Color and Discoloration Thresholds for Purchase of Representative Retail Ground Beef. Meat and Muscle Biology, 7(1)."
 
Added comment: 
_"In looking at the RIS files from Janeway and comparing it to one from Elsevier, I’m thinking it might be caused by listing all the authors as one entry, causing EndNote to see only one author with a lot of first and middle names. Elsevier has each author as a separate entry.
 
The editors would also like to have the article number and page range in the citation. I believe we’ve discussed adding this to the pages field."_

**Comment by ajrbyers** [comment]
@hinefuku here are some sample outputs with some updates. What do you think?

```bibtex
@article{olh12906,
	author = {Andy Admin and Mauro Sanchez and Jospeh Muller},
	title = {TEst},
	volume = {21},
	year = {2024},
	url = {http://localhost:8000/olh/article/id/12906/},
	issue = {1},
	doi = {10.16995/olh.12906},
	abstract = {&amp;lt;p&amp;gt;Test&amp;lt;/p&amp;gt;},
	month = {4},
	pages = {123},
	keywords = {dfsdfsdfs,dsfsdfs},
	issn = {2056-6700},
	publisher ={Open Library of Humanities},
	journal = {Open Library of Humanities}
}
```

```ris
TY  - JOUR
AB  - &lt;p&gt;Test&lt;/p&gt;
AU  - Andy Admin
AU  - Mauro Sanchez
AU  - Jospeh Muller
PA  - 2024
DA  - 2024/04/19
DO  - 10.16995/olh.12906
IS  - 1
VL  - 21
PB  - Open Library of Humanities
PY  - 2024
TI  - TEst
T2  - Open Library of Humanities
UR  - http://localhost:8000/olh/article/id/12906/
KW  - dfsdfsdfs
KW  - dsfsdfs
SP  - 1
EP  - 10
ER  -
```
