### ISSUE TITLE
update site map options to include CMS and static content

### ISSUE THREAD

**Issue by StephDriver** [openlibhums/janeway#3919]
Currently Janeway generates sitemaps for journal content, but not for the rest of the site (e.g. the static pages) nor for the Janeway back office.

Sitemaps are not required under WCAG2.2, but they are one of the recommended ways to achieve Guideline 2.4.5 and do improve accessibility.

**Comment by ajrbyers** [comment]
Include:

- News
- CMS Pages
- Static Views

**Comment by StephDriver** [comment]
from BirkbeckCTP/hourglass#349 

- [ ] need to ensure the sitemap has the language specified.

**Comment by StephDriver** [comment]
combined into 
- #4231 
and marked closed.
