### ISSUE TITLE
Author display at rejected & archived articles

### ISSUE THREAD

**Issue by Sebkrau** [openlibhums/janeway#3952]
**Is your feature request related to a problem? Please describe.**
We noticed the coloumn "ID" and "Identifier" are redundant in the rejected & archived articles display.

**Describe the solution you'd like**
There should be another coloumn using that space, one journal asked for there being authors displayed, so they have a better overview over who already submitted a paper and got declined. It makes it easier to check for double submissions.

**Describe alternatives you've considered**
Replace the "Identifier" or "ID" coloumn with an "Author" coloumn.

**Comment by S-Haime** [comment]
- DOI column defaults to JW ID when article is rejected / archived, thus redundant and taking up space.

- Should 'Published' and 'Rejected/Archived' be one page at all -> two pages? (Include author info, more space)
