### ISSUE TITLE
do these links (in same context) go to the same page? Figure Popups

### ISSUE THREAD

**Issue by StephDriver** [openlibhums/janeway#4149]
- #3939 
This turned out to be two separate issues, so this issue now handles 'example 2' as copied below

example 2 - figures using the same text and alt for the open popup link - I think this may be an XML problem as it seems all figures in this article are titled "Figure 1" such that all links to open a larger figure are also labeled for 'Figure 1'

https://www.iastatedigitalpress.com/mmb/article/id/11683/

<img width="698" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/5330770/471be260-70e0-497a-90dc-646883eba257">

<img width="699" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/5330770/53e4b18c-b3fb-422d-b3d3-0e27b7ea507c">

**Comment by StephDriver** [comment]
update:

Taking a look at the XML of the article, it does seem that is where the problem lies. Multiple figures all with the same "Figure 1" label, despite having different `fig id` 

e.g.

```xml
<fig id="f6"><label>Figure&#x00A0;1.</label>

<fig id="f7"><label>Figure&#x00A0;1.</label>

<fig id="f8"><label>Figure&#x00A0;1.</label
```

**Comment by StephDriver** [comment]
question - should we have some kind of xml validation script that checks for obvious A11y structural problems like this? Might it be useful for Phase 2 of the A11y Project to have some kind of file checker that looks for common errors, which then we can grow what if flags up over time?

**Comment by ajrbyers** [comment]
@StephDriver has confirmed in BRF that this an XML issue. This will be thrown back to Iowa.

Could checks like this be added as part of: https://github.com/openlibhums/janeway/issues/3180?

**Comment by StephDriver** [comment]
I have updated the Iowa project to show this issue is theirs not ours.  I have also updated #3180 as above.

No further action is required, so I and am now closing this.
