### ISSUE TITLE
Include preprint metrics in the article metrics box

### ISSUE THREAD

**Issue by mi-les** [openlibhums/janeway#4163]
**Describe the solution you'd like**
In ing.grid, the open peer review takes place on the preprint server and it can take quite a long time. Sometimes the preprints get a lot of views and downloads. Some authors would like to make these preprint views & downloads visible on the final article page, appearing side by side next to the article metrics in the metrics box.

**Comment by StephDriver** [comment]
Is this about showing the figures during peer review, or about shown any and all figures for preprint access at any point, including after article is finalised?

Thinking widely about the different uses people have for Janeway - do we need to make this distinction? There would be scenarios where someone might review preprints post finalisation - but where does that fit in the metrics - are we trying to show activity during peer-review, or 'all activity on any part of this article ever'?  it seems to me that the metrics collected can fall in three categories:


```mermaid
quadrantChart
    title Article Metrics
    x-axis Open Peer Review--> Published Article
    y-axis Final Article --> Preprints
    quadrant-1 Preprint Metrics post Publication
    quadrant-2 Metrics During Peer Review
    quadrant-3 n/a
    quadrant-4 Published Article Metrics

```

This affects the efficiency - if this is about the peer review process, then its a fixed number that it should be calculated once on publication and set alongside the final article metrics, but if it is a dynamic value where further views and downloads post-publication should be taken into account such that the two metrics should be connected.

**Comment by ajrbyers** [comment]
The preprint and article objects are separate. I’m not entirely sure it’s correct to display both together. This would be interesting to discuss in refinement.

**Comment by ajrbyers** [comment]
We discussed this in the backlog refinement meeting. We do have some updates coming to how we interlink article and preprints and this will become more prominent. We don't, however, want to include preprint metrics on the article page. @mi-les if you'd like to discuss it further please get in touch.
