### ISSUE TITLE
Review request page

### ISSUE THREAD

**Issue by LucasRabaey** [openlibhums/janeway#4254]
**Is your feature request related to a problem? Please describe.**
When sending a review request to a potential reviewer, they get a link to the review request page. The first thing they see there is the 'reviewer guidelines' section. Showing guidelines before having decided whether or not you want to review the article feels counterintuitive to us. 

**Describe the solution you'd like**
We like the idea of supplying some guidelines to our reviewers, but we feel they should be available/visible to them only after they have accepted the review. It is good to have them on the same page where they will submit the review, as is the case now.

**Describe alternatives you've considered**
Since we would like our reviewers to work with track changes in the article they review, it is not exactly an alternative for us to work with a review form (either using the review form options or supplying a review document).

**Comment by ajrbyers** [comment]
> **Is your feature request related to a problem? Please describe.** When sending a review request to a potential reviewer, they get a link to the review request page. The first thing they see there is the 'reviewer guidelines' section. Showing guidelines before having decided whether or not you want to review the article feels counterintuitive to us.
> 
> **Describe the solution you'd like** We like the idea of supplying some guidelines to our reviewers, but we feel they should be available/visible to them only after they have accepted the review. It is good to have them on the same page where they will submit the review, as is the case now.
> 
> **Describe alternatives you've considered** Since we would like our reviewers to work with track changes in the article they review, it is not exactly an alternative for us to work with a review form (either using the review form options or supplying a review document).

The flip-side of this, and the reason these are present, is so that reviewers are aware of how review is expected to be conducted. For example, some journals undertake open review and the reviewer needs to be aware of this before they accept or decline the request.

**Comment by LucasRabaey** [comment]
Ok, that's clear. Do you see another possible way to include more extensive guidelines only after the review has been accepted? I'm not entirely sure if the review form section is visible before making this decision?

Van: Andy Byers ***@***.***>
Verzonden: woensdag 5 juni 2024 13:58
Aan: BirkbeckCTP/janeway ***@***.***>
CC: Lucas Rabaey ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BirkbeckCTP/janeway] Review request page (Issue #4254)


Is your feature request related to a problem? Please describe. When sending a review request to a potential reviewer, they get a link to the review request page. The first thing they see there is the 'reviewer guidelines' section. Showing guidelines before having decided whether or not you want to review the article feels counterintuitive to us.

Describe the solution you'd like We like the idea of supplying some guidelines to our reviewers, but we feel they should be available/visible to them only after they have accepted the review. It is good to have them on the same page where they will submit the review, as is the case now.

Describe alternatives you've considered Since we would like our reviewers to work with track changes in the article they review, it is not exactly an alternative for us to work with a review form (either using the review form options or supplying a review document).

The flip-side of this, and the reason these are present, is so that reviewers are aware of how review is expected to be conducted. For example, some journals undertake open review and the reviewer needs to be aware of this before they accept or decline the request.

-

**Comment by mauromsl** [comment]
Hi @LucasRabaey, thanks for the report. We are going to integrate your feedback onto #4043 and come up with a redesign of the review request landing page. I've integrated your feedback there.
