### ISSUE TITLE
Reject and resubmit process improvement

### ISSUE THREAD

**Issue by S-Haime** [openlibhums/janeway#4310]
When a submission is set as 'reject and resubmit', would we want to include an option where the author is able to link the new submission to the old one to signal this to the editors? E.g. either 'resubmit' against the old submission or be able to signal this on the new submission (option to include the old submission ID?)

[See FD#8658 for some context / brief user comment.](https://janeway.freshdesk.com/a/tickets/8658)
("The software has a more limited range of decision options than we actually employ; so 'reject and resubmits' have to be coded there as straight 'reject'. ")

**Comment by ajrbyers** [comment]
We made a decision a long time ago not to all "reject and resubmit" as a decision so we wont be adding that as an option. In Janeway this is "Major Revisions" literally to avoid users creating multiple submission records.

@mauromsl is goign to write up an issue for cross-linking articles.
