### ISSUE TITLE
Triple-anonymous review

### ISSUE THREAD

**Issue by severett89** [openlibhums/janeway#4329]
**Is your feature request related to a problem? Please describe.**

Janeway currently does not have a triple-anonymous (TA) review option. Incoming journals to OLH have requested TA review.

**Describe the solution you'd like**
TA review means that editors cannot see the author's name on the initial submission of the manuscript until it is passed to peer review. In 'unassigned'/'editorial assignment' the author's name could be blanked out until the article is passed to review.

**Additional context**
While anonymity cannot be guaranteed on the manuscript file itself, e.g. Word document, it is for the journal to make clear to authors the submission reqs. of articles so that anonymity is not breached, and the consequences of breaching anonymity if the submission is made incorrectly.

**Comment by joemull** [comment]
Closed by https://github.com/openlibhums/janeway/pull/4434.
