### ISSUE TITLE
OLH theme mini-bar is wider than the main content

### ISSUE THREAD

**Issue by StephDriver** [openlibhums/janeway#4340]
In the OLH Theme, the minibar sticky div which contains the share links is wider (on both sides) than the rest of. hte content.  This means the edges of it are very tight against the sides of the window and it "looks a bit odd".

This issue was identified while working on the tab order of those share buttons ( #3933 ).

the three divs below are the problem (around line 103)

```html
<div data-sticky-container class="row">
            <div class="mini-bar sticky" data-sticky data-margin-top="0" data-sticky data-anchor="content">
                <div class="row">
```

Considering these as div1, div2 and div3, the expectation is for div1 to contain div 2 which in turn contains div3.  But instead:
- div2 overflows the bottom of div1
- div3 overflows to left and right of div 2.

<img width="481" alt="image" src="https://github.com/user-attachments/assets/9900e544-3d0e-4979-b96f-0d6506475beb">

**Comment by ajrbyers** [comment]
The sketch is useful but can you post a screenshot too?

**Comment by StephDriver** [comment]
<img width="882" alt="image" src="https://github.com/user-attachments/assets/810a59ef-8ed8-418a-9005-1a7ce6bb3cbc">


highlighting the borders:
<img width="424" alt="image" src="https://github.com/user-attachments/assets/4f67bff8-911e-4525-ad90-0eb96f3bfe28">


The main problem with this is the arrow for drop down for citing is now quite close to the edge of the window at some screen widths, no padding!  While the rest of the content has a small gutter between it and the edge.

**Comment by mauromsl** [comment]
suggested we address this directly in #3933

**Comment by joemull** [comment]
Backlog refinement: we suspect this has to do with improper combination of Foundation CSS classes causing a float + clearfix bug. (Haven't confirmed this though.)
