### ISSUE TITLE
Bring authentication and account pages into back office

### ISSUE THREAD

**Issue by joemull** [openlibhums/janeway#4380]
## Stories

As a designer and developer, I would like to improve the interfaces around authentication and account management without the overhead of updating and maintaining three separate sets of templates that each use different CSS frameworks and methodologies. The current setup is especially expensive if you think about the fact that we usually use frontend theme CSS for presentational and content-focused things, but the account pages are interactive, so we need to create interactive components and pages that handle forms including patterns like selection, confirmation, deletion, etc. An example is the work I am doing for #3168.

As any Janeway user, I would like to navigate things like registering, resetting my password, and editing my profile without being confused about where I am, or about how to get back to where I was before. Basically, I shouldn't have to deal with repeated switching between theme layers, and at the end I should be redirected to where I was, or a clear button that lets me get back to the homepage (if I was on the public-facing site) or the manager or dashboard (if I was in the back office).

As a theme designer for Janeway journal sites and articles, I do not want to have to redesign interaction-heavy pages to get a consistent look and feel. It would be nice if the themes were lighter and easier to cover with fewer templates and CSS components, and I could delegate the interactive pages to a single back office theme.

## Proposed solution
- [x] Create or update back-office templates for each of these views:
      - user_login
      - ~user_login_orcid~ - not needed as no template used
      - ~user_logout~ - not needed as no template used
      - get_reset_token
      - reset_password
      - register
      - orcid_registration
      - activate_account
      - edit_profile
- [x] Deprecate the corresponding templates in the theme template directories
- [x] Write view tests to check that each of these views finds the correct back-office template
- [x] Manually test the new interfaces, perhaps with some user testing by people who have never used Janeway

## Other context
In addition to user testing after the change, I think it would be beneficial to do some rapid UX research beforehand on this one. Methods that might work well:

- [First click test](https://www.optimalworkshop.com/101guides/first-click-testing-101), to see if casual users know how to get between the front and back offices
- User journey mapping, to pin down the exact routes users take that bring them through the auth and account pages

**Comment by mauromsl** [comment]
we should not delete the theme templates as they might be in use by self-hosted Janeway users
