### ISSUE TITLE
OLH website Contact Us form not working

### ISSUE THREAD

**Issue by the-blochian** [openlibhums/janeway#4395]
I've heard from a UK academic that she had a bounce when trying to use the Contact Us form on the OLH website (this page: https://www.openlibhums.org/contact/).

Would someone be able to check that the form builder is working OK? Slightly worried that other people may have experienced a bounce also but not found my BBK email address online to get in touch.

Thanks! :)

**Comment by ajrbyers** [comment]
I looked into this and found that the form isn't working. I've reported this on Hourglass (https://github.com/openlibhums/hourglass/issues/386). @the-blochian suspects this may be what the person was reporting.

**Comment by ajrbyers** [comment]
Closed by https://github.com/openlibhums/hourglass/pull/391
