### ISSUE TITLE
Peer Review Invitations not sending (reviewers only receiving reminders)

### ISSUE THREAD

**Issue by the-blochian** [openlibhums/janeway#4404]
Klaus Abels (EiC of Zygon) reports feedback from a number of potential reviewers that they only received our reminder to review a paper via Janeway but not the original invitation.

**Comment by ajrbyers** [comment]
@the-blochian Klaus needs to report these to the service desk, we need specific examples within a 7 day time frame so we can workout why this is happening.

**Comment by the-blochian** [comment]
Aha, apologies! Will ask him to do that, please go ahead and delete this.
