### ISSUE TITLE
Italics and ampersand in News title not rendering properly

### ISSUE THREAD

**Issue by pgoussy** [openlibhums/janeway#4467]
**Describe the bug**
I created a News item whose title field contained both italics and an ampersand character. On the journal's homepage, the italics was displayed as visible `<em>` tags, and the ampersand was displayed as an `&amp;` entity. 

**Janeway version**
1.7.0

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/mp/
2. Scroll down to 'Latest News Posts'
3. See error (however, I've already revised the title of the News item to avoid the use of italics or ampersand, so that they don't have visible errors live on their homepage. See screenshots below

**Screenshots**
![image](https://github.com/user-attachments/assets/fcd5631a-1f70-48ce-9a2d-c18daf491f34)
![image](https://github.com/user-attachments/assets/04d4ba90-a060-4fc2-b0a9-540395298c49)

**Comment by ajrbyers** [comment]
Thanks @pgoussy ill look into this and get back to you asap.
